server:
  port: 8081
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.session.SessionAutoConfiguration
  thymeleaf:
    cache: false
#  redis:
#    host: master-ump-server
#    port: 6379
#    password: ump@2018 206.189.41.190
  http:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  messages:
      basename: messages/messages
      cache-seconds: -1
      encoding: UTF-8
#commondEndpointUrl: http://206.189.41.190:8091/api
commondEndpointUrl: http://localhost:8091/api
apiEndpointUrl: http://localhost:8092/api
